name: lolcat
base: core18
version: git
summary: Rainbows and unicorns!
description: |
  Rainbow-colored output.

grade: stable
confinement: strict

parts:
  lolcat:
    plugin: dump
    source: .
    override-build: |
      gem build lolcat.gemspec
      gem install lolcat-*.gem -i $SNAPCRAFT_PART_INSTALL
    build-packages: [gcc, libc6-dev, make, ruby-dev]
    stage-packages: [ruby]

apps:
  lolcat:
    command: lolcat
    environment:
      RUBYLIB: $SNAP/usr/lib/ruby/2.5.0:$SNAP/usr/lib/x86_64-linux-gnu/ruby/2.5.0
      GEM_HOME: $SNAP/gems
      GEM_PATH: $SNAP
    command: ruby $SNAP/bin/lolcat